version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: social-media-platform
    ports:
      - '3000:3000'
    command: "npm run dev"
    volumes:
      - ./:/app